### ISSUE TITLE
[Enhancement] Get away from Appointment Hour Booking

### ISSUE THREAD

**Issue by skjerns** [leih-lokal/scripts#12]
For historical reasons, we are still using the AppointmentHourBookings plugin to manage our reservations. We needed fine grained timeslots during corona, now we don't any longer. However, the thing costs us 5€/month and I don't think it's worth the money. So lets replace it with something free or better!

The current workflow is as follows:

1. People make a reservation on our [Klicken&Abholen](https://www.buergerstiftung-karlsruhe.de/klicken-abholen/) page
2. The entries are saved in a MySQL database
3. The confirmation page has a hidden GitHub Webhook that triggers this workflow
4. The code in this folder gets executed: https://github.com/leih-lokal/scripts/tree/master/WPAppointmentManager
5. The [code](https://github.com/leih-lokal/scripts/tree/master/WPAppointmentManager) retrieved the entries from the MySQL database checks in the CouchDB if the items are available, puts them as `reserviert` and sends a confirmation or failure email to the user.

Solution proposal:
1. Find another plugin that has similar support (maybe even with a WooCommerce connector?)
2. Adapt the above mentioned script so that it works with the new plugin
3. Meet with the IT team to have a beer paid by all the money that is now saved

Alternative:
- Programm a small PHP/JS web page that does all of that, with direct connection to the db. Should actually not be very difficult.

**Comment by muety** [comment]
Plugin is used for [here](https://buergerstiftung-karlsruhe.de/klicken-abholen/) and [here](https://buergerstiftung-karlsruhe.de/freiraeume/buchung-anfragen/) (with corresponding calendar displayed [here](https://buergerstiftung-karlsruhe.de/freiraeume/buchungskalender-frei_raeume/)).

**Comment by skjerns** [comment]
That sounds good!

>   * We are possibly using these premium features
>     
>     * _Basic Form Fields_ (?)
>     * _Conditional Rules and Fields Validation_ (where and how exactly?)
>     * _Export Information to CSV Files_ (for [`create_clickcollect_overview`](https://github.com/leih-lokal/scripts/blob/master/create_clickcollect_overview.py))
>       
>       * 👉 Might get replaced by custom API / database queries
> * Plugin is used for [here](https://buergerstiftung-karlsruhe.de/klicken-abholen/) and [here](https://buergerstiftung-karlsruhe.de/freiraeume/buchung-anfragen/) (with corresponding calendar displayed [here](https://buergerstiftung-karlsruhe.de/freiraeume/buchungskalender-frei_raeume/)).
> * The webhook is triggered for **every** `GET` request to https://buergerstiftung-karlsruhe.de/leihlokal/click-collect-bestaetigung/
> * Some plugins support ics / ical, so we might be able to get rid of the CSV export and directly sync the booking in our Outlook / Thunderbird calendar

Some features we are also using (I don't know if they are premium, [but I think so](https://apphourbooking.dwbooster.com/download)):
* iCal import: To see when the rooms are available for booking, we import the internal booking calendar
   * we could replace the Frei_Räume calendar plugin with something completely different to solve this
* Additional booking status
   * This is to indicate whether bookings have been accepted or not for the AppointmentManager. I think this could be solved without these additional status as well
* Cancellation link
   * people can cancel their appointsments. I don't think it's used very often, mostly people just don't show up at all.

I actually think that all of these are circumventable/solvable

**Comment by muety** [comment]
So in summary, when downgrading to the free version, we'd definitely have to come up with a custom-built solution for:
- CSV exports
- iCal imports
- Optional: cancellation link (probably quite easy to implement, though)

For _Additional booking status_, we can probably just go without. For _Conditional Rules and Fields Validation_  don't know.

Sounds like a quite a bit of work. Unfortunately, there doesn't seem to be a free plugin alternative that provides those features either.

**Comment by skjerns** [comment]
Thanks to @muety, we have now switched to a life time license of appointment booking hours so there is no more issue with just keeping the current workflow going :)

huge props to muety for setting this in motion!
