### ISSUE TITLE
`renewed_on` status not properly respected by user deletion script

### ISSUE THREAD

**Issue by muety** [leih-lokal/scripts#20]
A leih.lokal colleague reported a potential bug in the user deletion script.

Given a user who had renewed their membership at least once some time in the past, the user will be listed in the deletion prompt after >= 2 years _without_ having received another reminder e-mail before.

We might want to revise the entire e-mail inbox / outbox scraping logic.

**Comment by muety** [comment]
@skjerns Can you remember what was the rationale behind setting `cutoff_days=9999` [here](https://github.com/leih-lokal/scripts/blob/72b3955ccb839f4d850a5a85733c5cd7cad1bb27/daily_tasks.py#L176)? That's was causing the described bug.

**Comment by skjerns** [comment]
Nope. Maybe because leaving it at None caused Ann exception?
