### ISSUE TITLE
Please show exact Status, not only "verliehen"

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/scripts#4]
Hi,

I think it would be better to show "reserviert", "nicht verleihbar" or "verliehen" instead of only "verliehen". 
https://github.com/leih-lokal/scripts/blob/master/daily_tasks.py#L265
Is it possible to show when the status was last changed? It would then be possible to see how long an article is already reserved. I think this could be handy for articles that were reserved manually.

Thanks :)

**Comment by skjerns** [comment]
mhh, that should already be the case?

But I can check that again soon

https://github.com/leih-lokal/scripts/blob/9b050ad4534994c7b24b7ec06d41197cc8dfdcbc/daily_tasks.py#L283

https://github.com/leih-lokal/scripts/blob/9b050ad4534994c7b24b7ec06d41197cc8dfdcbc/daily_tasks.py#L279

**Comment by daniel17903** [comment]
@skjerns There is a „last_update“ field in each item with a timestamp of the last update.
