### ISSUE TITLE
Show Säumnisgebühr in Table

### ISSUE THREAD

**Issue by christianstarck** [leih-lokal/scripts#5]
Maybe it's possible to show a recommended Defaultfee if user is too late. So it's easier for us to know who is too late. 

https://github.com/leih-lokal/scripts/blob/0fa58154d9bf990b1448badb5af4a8d209b9dd6f/create_clickcollect_overview.py#L194

**Comment by skjerns** [comment]
That's a good idea! 
I will try to fit it into the table, however, as I remember, the table is already super full and there's little space to add another column. I'll try!
